jrl-mal: maal::boost Namespace Reference
maal::boost Namespace Reference
Classes
class Matrix
Matrix class that include the boost::ublas::matrix.
class MatrixSvd
class Vector
Vector class that include the boost::ublas::vector.
Typedefs
typedef double FloatType
Native type of the Matrix and Vector classes.
Enumerations
enum DisplayType {
SIMPLE,
COMPLET,
CPP,
MATLAB
}
Option of display for the matrix and vector output (cout<<).
Functions
DisplayType setDisplayType (const DisplayType type, const bool read=false)
Modify the display type.
DisplayType getDisplayType (void)
Get the current display type.
std::ostream & operator<< (std::ostream &os, DisplayType disp)
The second solution is to pass the DisplayType directly to the ouput operator: cout << DisplayType.
Typedef Documentation
typedef double maal::boost::FloatType
Native type of the Matrix and Vector classes.
Change here if a float or a double lib is needed.
Enumeration Type Documentation
enum maal::boost::DisplayType
Option of display for the matrix and vector output (cout<<).
Two solutions can be usedto modify the display. The static function setDisplayType(DisplayType) is the classical solution. The second solution is to pass the DisplayType directly to the ouput operator: cout << DisplayType
Enumerator:
SIMPLE
COMPLET
CPP
MATLAB
Function Documentation
DisplayType maal::boost::getDisplayType (void) [inline]
Get the current display type.
References setDisplayType(), and SIMPLE.
std::ostream& maal::boost::operator<< (std::ostream & os, DisplayType disp) [inline]
The second solution is to pass the DisplayType directly to the ouput operator: cout << DisplayType.
References setDisplayType().
DisplayType maal::boost::setDisplayType (const DisplayType type, const bool read = false) [inline]
Modify the display type.
References MATLAB.
Referenced by getDisplayType(), and operator<<().